#ifndef JAVA_CLASSES_H
#define JAVA_CLASSES_H
#include <edu_monash_infotech_OWLAPIWrapper.h>
#include <java_lang_Object.h>
#include <java_lang_String.h>
#include <java_lang_Class.h>
#include <java_io_Serializable.h>
#include <java_lang_Comparable.h>
#include <java_lang_CharSequence.h>
#include <java_nio_charset_Charset.h>
#include <java_lang_StringBuffer.h>
#include <java_lang_StringBuilder.h>
#include <java_util_Locale.h>
#include <java_util_Comparator.h>
#include <java_lang_reflect_GenericDeclaration.h>
#include <java_lang_reflect_Type.h>
#include <java_lang_reflect_AnnotatedElement.h>
#include <java_lang_ClassLoader.h>
#include <java_lang_reflect_TypeVariable.h>
#include <java_lang_Package.h>
#include <java_lang_reflect_Method.h>
#include <java_lang_reflect_Constructor.h>
#include <java_lang_reflect_Field.h>
#include <java_io_InputStream.h>
#include <java_net_URL.h>
#include <java_security_ProtectionDomain.h>
#include <java_lang_annotation_Annotation.h>
#include <java_nio_CharBuffer.h>
#include <java_nio_ByteBuffer.h>
#include <java_util_Set.h>
#include <java_util_SortedMap.h>
#include <java_nio_charset_CharsetDecoder.h>
#include <java_nio_charset_CharsetEncoder.h>
#include <java_lang_AbstractStringBuilder.h>
#include <java_lang_Appendable.h>
#include <java_lang_Cloneable.h>
#include <java_util_Enumeration.h>
#include <java_lang_reflect_AccessibleObject.h>
#include <java_lang_reflect_Member.h>
#include <java_io_Closeable.h>
#include <java_net_URLStreamHandler.h>
#include <java_net_URI.h>
#include <java_net_URLConnection.h>
#include <java_net_Proxy.h>
#include <java_net_URLStreamHandlerFactory.h>
#include <java_security_CodeSource.h>
#include <java_security_PermissionCollection.h>
#include <java_security_Principal.h>
#include <java_security_Permission.h>
#include <java_nio_Buffer.h>
#include <java_lang_Readable.h>
#include <java_nio_ByteOrder.h>
#include <java_nio_ShortBuffer.h>
#include <java_nio_IntBuffer.h>
#include <java_nio_LongBuffer.h>
#include <java_nio_FloatBuffer.h>
#include <java_nio_DoubleBuffer.h>
#include <java_util_Collection.h>
#include <java_util_Iterator.h>
#include <java_util_Map.h>
#include <java_nio_charset_CoderResult.h>
#include <java_nio_charset_CodingErrorAction.h>
#include <java_net_FileNameMap.h>
#include <java_io_OutputStream.h>
#include <java_net_ContentHandlerFactory.h>
#include <java_net_Proxy__Type.h>
#include <java_net_SocketAddress.h>
#include <java_security_cert_Certificate.h>
#include <java_security_CodeSigner.h>
#include <java_security_Guard.h>
#include <java_lang_Iterable.h>
#include <java_io_Flushable.h>
#include <java_net_ContentHandler.h>
#include <java_lang_Enum.h>
#include <java_security_PublicKey.h>
#include <java_security_cert_CertPath.h>
#include <java_security_Timestamp.h>
#include <java_security_Key.h>
#include <java_util_List.h>
#include <java_util_Date.h>
#include <java_util_ListIterator.h>
#endif
