#ifndef JAVA_CLASSES_H
#define JAVA_CLASSES_H
#include <edu_monash_infotech_OWLAPIWrapper.h>
#include <java_lang_Object.h>
#include <java_lang_String.h>
#include <org_semanticweb_owlapi_model_OWLClass.h>
#include <java_lang_Class.h>
#include <java_io_Serializable.h>
#include <java_lang_Comparable.h>
#include <java_lang_CharSequence.h>
#include <java_nio_charset_Charset.h>
#include <java_lang_StringBuffer.h>
#include <java_lang_StringBuilder.h>
#include <java_util_Locale.h>
#include <java_util_Comparator.h>
#include <org_semanticweb_owlapi_model_OWLClassExpression.h>
#include <org_semanticweb_owlapi_model_OWLLogicalEntity.h>
#include <org_semanticweb_owlapi_model_OWLNamedObject.h>
#include <org_semanticweb_owlapi_model_OWLOntology.h>
#include <java_util_Set.h>
#include <java_lang_reflect_GenericDeclaration.h>
#include <java_lang_reflect_Type.h>
#include <java_lang_reflect_AnnotatedElement.h>
#include <java_lang_ClassLoader.h>
#include <java_lang_reflect_TypeVariable.h>
#include <java_lang_Package.h>
#include <java_lang_reflect_Method.h>
#include <java_lang_reflect_Constructor.h>
#include <java_lang_reflect_Field.h>
#include <java_io_InputStream.h>
#include <java_net_URL.h>
#include <java_security_ProtectionDomain.h>
#include <java_lang_annotation_Annotation.h>
#include <java_nio_CharBuffer.h>
#include <java_nio_ByteBuffer.h>
#include <java_util_SortedMap.h>
#include <java_nio_charset_CharsetDecoder.h>
#include <java_nio_charset_CharsetEncoder.h>
#include <java_lang_AbstractStringBuilder.h>
#include <java_lang_Appendable.h>
#include <java_lang_Cloneable.h>
#include <org_semanticweb_owlapi_model_OWLObject.h>
#include <org_semanticweb_owlapi_model_OWLPropertyRange.h>
#include <org_semanticweb_owlapi_model_SWRLPredicate.h>
#include <org_semanticweb_owlapi_model_OWLClassExpressionVisitor.h>
#include <org_semanticweb_owlapi_model_OWLClassExpressionVisitorEx.h>
#include <org_semanticweb_owlapi_model_ClassExpressionType.h>
#include <org_semanticweb_owlapi_model_OWLEntity.h>
#include <org_semanticweb_owlapi_model_OWLNamedObjectVisitor.h>
#include <org_semanticweb_owlapi_model_IRI.h>
#include <org_semanticweb_owlapi_model_AxiomType.h>
#include <org_semanticweb_owlapi_model_OWLObjectPropertyExpression.h>
#include <org_semanticweb_owlapi_model_OWLDataProperty.h>
#include <org_semanticweb_owlapi_model_OWLIndividual.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationProperty.h>
#include <org_semanticweb_owlapi_model_OWLDatatype.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationSubject.h>
#include <org_semanticweb_owlapi_model_OWLAnonymousIndividual.h>
#include <org_semanticweb_owlapi_model_OWLOntologyManager.h>
#include <org_semanticweb_owlapi_model_OWLOntologyID.h>
#include <org_semanticweb_owlapi_model_OWLAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDataPropertyExpression.h>
#include <java_util_Collection.h>
#include <java_util_Iterator.h>
#include <java_util_Enumeration.h>
#include <java_lang_reflect_AccessibleObject.h>
#include <java_lang_reflect_Member.h>
#include <java_io_Closeable.h>
#include <java_net_URLStreamHandler.h>
#include <java_net_URI.h>
#include <java_net_URLConnection.h>
#include <java_net_Proxy.h>
#include <java_net_URLStreamHandlerFactory.h>
#include <java_security_CodeSource.h>
#include <java_security_PermissionCollection.h>
#include <java_security_Principal.h>
#include <java_security_Permission.h>
#include <java_nio_Buffer.h>
#include <java_lang_Readable.h>
#include <java_nio_ByteOrder.h>
#include <java_nio_ShortBuffer.h>
#include <java_nio_IntBuffer.h>
#include <java_nio_LongBuffer.h>
#include <java_nio_FloatBuffer.h>
#include <java_nio_DoubleBuffer.h>
#include <java_util_Map.h>
#include <java_nio_charset_CoderResult.h>
#include <java_nio_charset_CodingErrorAction.h>
#include <org_semanticweb_owlapi_model_OWLObjectVisitor.h>
#include <org_semanticweb_owlapi_model_OWLObjectVisitorEx.h>
#include <org_semanticweb_owlapi_model_OWLObjectIntersectionOf.h>
#include <org_semanticweb_owlapi_model_OWLObjectUnionOf.h>
#include <org_semanticweb_owlapi_model_OWLObjectComplementOf.h>
#include <org_semanticweb_owlapi_model_OWLObjectSomeValuesFrom.h>
#include <org_semanticweb_owlapi_model_OWLObjectAllValuesFrom.h>
#include <org_semanticweb_owlapi_model_OWLObjectHasValue.h>
#include <org_semanticweb_owlapi_model_OWLObjectMinCardinality.h>
#include <org_semanticweb_owlapi_model_OWLObjectExactCardinality.h>
#include <org_semanticweb_owlapi_model_OWLObjectMaxCardinality.h>
#include <org_semanticweb_owlapi_model_OWLObjectHasSelf.h>
#include <org_semanticweb_owlapi_model_OWLObjectOneOf.h>
#include <org_semanticweb_owlapi_model_OWLDataSomeValuesFrom.h>
#include <org_semanticweb_owlapi_model_OWLDataAllValuesFrom.h>
#include <org_semanticweb_owlapi_model_OWLDataHasValue.h>
#include <org_semanticweb_owlapi_model_OWLDataMinCardinality.h>
#include <org_semanticweb_owlapi_model_OWLDataExactCardinality.h>
#include <org_semanticweb_owlapi_model_OWLDataMaxCardinality.h>
#include <java_lang_Enum.h>
#include <org_semanticweb_owlapi_model_OWLEntityVisitor.h>
#include <org_semanticweb_owlapi_model_OWLEntityVisitorEx.h>
#include <org_semanticweb_owlapi_model_EntityType.h>
#include <org_semanticweb_owlapi_model_OWLObjectProperty.h>
#include <org_semanticweb_owlapi_model_OWLNamedIndividual.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationValue.h>
#include <java_io_File.h>
#include <org_semanticweb_owlapi_model_OWLPropertyExpression.h>
#include <org_semanticweb_owlapi_model_OWLProperty.h>
#include <org_semanticweb_owlapi_model_OWLPropertyAssertionObject.h>
#include <org_semanticweb_owlapi_model_OWLIndividualVisitor.h>
#include <org_semanticweb_owlapi_model_OWLIndividualVisitorEx.h>
#include <org_semanticweb_owlapi_model_OWLLiteral.h>
#include <org_semanticweb_owlapi_model_OWLDataRange.h>
#include <org_semanticweb_owlapi_vocab_OWL2Datatype.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationObject.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationSubjectVisitor.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationSubjectVisitorEx.h>
#include <org_semanticweb_owlapi_model_NodeID.h>
#include <org_semanticweb_owlapi_model_OWLOntologySetProvider.h>
#include <org_semanticweb_owlapi_model_OWLDataFactory.h>
#include <org_semanticweb_owlapi_io_OWLOntologyDocumentSource.h>
#include <org_semanticweb_owlapi_model_OWLOntologyLoaderConfiguration.h>
#include <org_semanticweb_owlapi_model_OWLImportsDeclaration.h>
#include <java_util_List.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChange.h>
#include <org_semanticweb_owlapi_model_OWLOntologyFormat.h>
#include <java_io_OutputStream.h>
#include <org_semanticweb_owlapi_io_OWLOntologyDocumentTarget.h>
#include <org_semanticweb_owlapi_model_OWLOntologyIRIMapper.h>
#include <org_semanticweb_owlapi_model_OWLOntologyFactory.h>
#include <org_semanticweb_owlapi_model_OWLOntologyStorer.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeListener.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeBroadcastStrategy.h>
#include <org_semanticweb_owlapi_model_ImpendingOWLOntologyChangeListener.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangesVetoedListener.h>
#include <org_semanticweb_owlapi_model_MissingImportListener.h>
#include <org_semanticweb_owlapi_model_OWLOntologyLoaderListener.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeProgressListener.h>
#include <org_semanticweb_owlapi_model_OWLAxiomVisitor.h>
#include <org_semanticweb_owlapi_model_OWLAxiomVisitorEx.h>
#include <java_lang_Iterable.h>
#include <java_net_FileNameMap.h>
#include <java_net_ContentHandlerFactory.h>
#include <java_net_Proxy__Type.h>
#include <java_net_SocketAddress.h>
#include <java_security_cert_Certificate.h>
#include <java_security_CodeSigner.h>
#include <java_security_Guard.h>
#include <org_semanticweb_owlapi_model_OWLDataVisitor.h>
#include <org_semanticweb_owlapi_model_OWLPropertyExpressionVisitor.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationAxiomVisitor.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationValueVisitor.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationObjectVisitor.h>
#include <org_semanticweb_owlapi_model_SWRLObjectVisitor.h>
#include <org_semanticweb_owlapi_model_OWLDataVisitorEx.h>
#include <org_semanticweb_owlapi_model_OWLPropertyExpressionVisitorEx.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationObjectVisitorEx.h>
#include <org_semanticweb_owlapi_model_SWRLObjectVisitorEx.h>
#include <org_semanticweb_owlapi_model_OWLNamedObjectVisitorEx.h>
#include <org_semanticweb_owlapi_model_OWLNaryBooleanClassExpression.h>
#include <org_semanticweb_owlapi_model_OWLBooleanClassExpression.h>
#include <org_semanticweb_owlapi_model_OWLQuantifiedObjectRestriction.h>
#include <org_semanticweb_owlapi_model_OWLHasValueRestriction.h>
#include <org_semanticweb_owlapi_model_OWLObjectCardinalityRestriction.h>
#include <org_semanticweb_owlapi_model_OWLRestriction.h>
#include <org_semanticweb_owlapi_model_OWLAnonymousClassExpression.h>
#include <org_semanticweb_owlapi_model_OWLQuantifiedDataRestriction.h>
#include <org_semanticweb_owlapi_model_OWLDataCardinalityRestriction.h>
#include <org_semanticweb_owlapi_vocab_OWLRDFVocabulary.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationValueVisitorEx.h>
#include <java_io_FilenameFilter.h>
#include <java_io_FileFilter.h>
#include <org_semanticweb_owlapi_model_OWLDataRangeVisitor.h>
#include <org_semanticweb_owlapi_model_OWLDataRangeVisitorEx.h>
#include <org_semanticweb_owlapi_model_DataRangeType.h>
#include <java_util_regex_Pattern.h>
#include <org_semanticweb_owlapi_vocab_OWL2Datatype__Category.h>
#include <org_semanticweb_owlapi_model_SWRLDataFactory.h>
#include <org_semanticweb_owlapi_model_PrefixManager.h>
#include <org_semanticweb_owlapi_model_OWLObjectInverseOf.h>
#include <org_semanticweb_owlapi_model_OWLDataOneOf.h>
#include <org_semanticweb_owlapi_model_OWLDataComplementOf.h>
#include <org_semanticweb_owlapi_model_OWLDatatypeRestriction.h>
#include <org_semanticweb_owlapi_vocab_OWLFacet.h>
#include <org_semanticweb_owlapi_model_OWLFacetRestriction.h>
#include <org_semanticweb_owlapi_model_OWLDataUnionOf.h>
#include <org_semanticweb_owlapi_model_OWLDataIntersectionOf.h>
#include <org_semanticweb_owlapi_model_OWLDeclarationAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubClassOfAxiom.h>
#include <org_semanticweb_owlapi_model_OWLEquivalentClassesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDisjointClassesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDisjointUnionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubObjectPropertyOfAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubPropertyChainOfAxiom.h>
#include <org_semanticweb_owlapi_model_OWLEquivalentObjectPropertiesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDisjointObjectPropertiesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLInverseObjectPropertiesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLObjectPropertyDomainAxiom.h>
#include <org_semanticweb_owlapi_model_OWLObjectPropertyRangeAxiom.h>
#include <org_semanticweb_owlapi_model_OWLFunctionalObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLInverseFunctionalObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLReflexiveObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLIrreflexiveObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSymmetricObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLAsymmetricObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLTransitiveObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubDataPropertyOfAxiom.h>
#include <org_semanticweb_owlapi_model_OWLEquivalentDataPropertiesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDisjointDataPropertiesAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDataPropertyDomainAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDataPropertyRangeAxiom.h>
#include <org_semanticweb_owlapi_model_OWLFunctionalDataPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLHasKeyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDatatypeDefinitionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSameIndividualAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDifferentIndividualsAxiom.h>
#include <org_semanticweb_owlapi_model_OWLClassAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLObjectPropertyAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLNegativeObjectPropertyAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDataPropertyAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLNegativeDataPropertyAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLAnnotation.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationPropertyDomainAxiom.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationPropertyRangeAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubAnnotationPropertyOfAxiom.h>
#include <java_io_Reader.h>
#include <org_semanticweb_owlapi_model_OWLOntologyLoaderConfiguration__MissingOntologyHeaderStrategy.h>
#include <java_util_ListIterator.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeVisitor.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeVisitorEx.h>
#include <org_semanticweb_owlapi_vocab_PrefixOWLOntologyFormat.h>
#include <org_semanticweb_owlapi_io_OWLOntologyLoaderMetaData.h>
#include <java_io_Flushable.h>
#include <java_io_Writer.h>
#include <org_semanticweb_owlapi_model_OWLOntologyFactory__OWLOntologyCreationHandler.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeVetoException.h>
#include <org_semanticweb_owlapi_model_MissingImportEvent.h>
#include <org_semanticweb_owlapi_model_OWLOntologyLoaderListener__LoadingStartedEvent.h>
#include <org_semanticweb_owlapi_model_OWLOntologyLoaderListener__LoadingFinishedEvent.h>
#include <org_semanticweb_owlapi_model_SWRLRule.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationAxiomVisitorEx.h>
#include <java_net_ContentHandler.h>
#include <java_security_PublicKey.h>
#include <java_security_cert_CertPath.h>
#include <java_security_Timestamp.h>
#include <org_semanticweb_owlapi_model_SWRLClassAtom.h>
#include <org_semanticweb_owlapi_model_SWRLDataRangeAtom.h>
#include <org_semanticweb_owlapi_model_SWRLObjectPropertyAtom.h>
#include <org_semanticweb_owlapi_model_SWRLDataPropertyAtom.h>
#include <org_semanticweb_owlapi_model_SWRLBuiltInAtom.h>
#include <org_semanticweb_owlapi_model_SWRLVariable.h>
#include <org_semanticweb_owlapi_model_SWRLIndividualArgument.h>
#include <org_semanticweb_owlapi_model_SWRLLiteralArgument.h>
#include <org_semanticweb_owlapi_model_SWRLSameIndividualAtom.h>
#include <org_semanticweb_owlapi_model_SWRLDifferentIndividualsAtom.h>
#include <org_semanticweb_owlapi_model_OWLQuantifiedRestriction.h>
#include <org_semanticweb_owlapi_model_OWLCardinalityRestriction.h>
#include <org_semanticweb_owlapi_vocab_Namespaces.h>
#include <java_util_regex_Matcher.h>
#include <org_semanticweb_owlapi_model_SWRLIArgument.h>
#include <org_semanticweb_owlapi_model_SWRLDArgument.h>
#include <org_semanticweb_owlapi_model_OWLNaryDataRange.h>
#include <org_semanticweb_owlapi_model_OWLClassAxiom.h>
#include <org_semanticweb_owlapi_model_OWLNaryClassAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLObjectPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLNaryPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLPropertyDomainAxiom.h>
#include <org_semanticweb_owlapi_model_OWLPropertyRangeAxiom.h>
#include <org_semanticweb_owlapi_model_OWLObjectPropertyCharacteristicAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubClassOfAxiomShortCut.h>
#include <org_semanticweb_owlapi_model_OWLDataPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLDataPropertyCharacteristicAxiom.h>
#include <org_semanticweb_owlapi_model_OWLLogicalAxiom.h>
#include <org_semanticweb_owlapi_model_OWLNaryIndividualAxiom.h>
#include <org_semanticweb_owlapi_model_OWLIndividualAxiom.h>
#include <org_semanticweb_owlapi_model_OWLPropertyAssertionAxiom.h>
#include <org_semanticweb_owlapi_model_OWLAnnotationAxiom.h>
#include <org_semanticweb_owlapi_model_AddAxiom.h>
#include <org_semanticweb_owlapi_model_RemoveAxiom.h>
#include <org_semanticweb_owlapi_model_SetOntologyID.h>
#include <org_semanticweb_owlapi_model_AddImport.h>
#include <org_semanticweb_owlapi_model_RemoveImport.h>
#include <org_semanticweb_owlapi_model_AddOntologyAnnotation.h>
#include <org_semanticweb_owlapi_model_RemoveOntologyAnnotation.h>
#include <org_semanticweb_owlapi_model_OWLOntologyChangeException.h>
#include <java_lang_Throwable.h>
#include <org_semanticweb_owlapi_model_OWLOntologyCreationException.h>
#include <org_semanticweb_owlapi_model_OWLOntologyLoaderListener__LoadingEvent.h>
#include <org_semanticweb_owlapi_model_SWRLObject.h>
#include <java_security_Key.h>
#include <java_util_Date.h>
#include <org_semanticweb_owlapi_model_SWRLUnaryAtom.h>
#include <org_semanticweb_owlapi_model_SWRLBinaryAtom.h>
#include <org_semanticweb_owlapi_model_SWRLAtom.h>
#include <java_util_regex_MatchResult.h>
#include <org_semanticweb_owlapi_model_SWRLArgument.h>
#include <org_semanticweb_owlapi_model_OWLNaryAxiom.h>
#include <org_semanticweb_owlapi_model_OWLSubClassOfAxiomSetShortCut.h>
#include <org_semanticweb_owlapi_model_OWLPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLUnaryPropertyAxiom.h>
#include <org_semanticweb_owlapi_model_OWLAxiomChange.h>
#include <org_semanticweb_owlapi_model_ImportChange.h>
#include <org_semanticweb_owlapi_model_OWLRuntimeException.h>
#include <java_io_PrintStream.h>
#include <java_io_PrintWriter.h>
#include <java_lang_StackTraceElement.h>
#include <org_semanticweb_owlapi_model_OWLException.h>
#include <java_lang_RuntimeException.h>
#include <java_io_FilterOutputStream.h>
#include <java_lang_Exception.h>
#endif
